// ─── 포켓몬 카드 세트 카탈로그 ──────────────────────────────
// 시대별로 그룹화. 카드 출품 시 세트 선택용. 추가는 자유롭게 가능.

export const POKEMON_SETS = {
  'WotC 초기 (1999-2003)': [
    'Base Set',
    'Base Set 1st Edition',
    'Base Set Shadowless',
    'Base Set 2',
    'Jungle',
    'Jungle 1st Edition',
    'Fossil',
    'Fossil 1st Edition',
    'Team Rocket',
    'Team Rocket 1st Edition',
    'Gym Heroes',
    'Gym Heroes 1st Edition',
    'Gym Challenge',
    'Gym Challenge 1st Edition',
  ],
  'Neo (2000-2002)': [
    'Neo Genesis',
    'Neo Genesis 1st Edition',
    'Neo Discovery',
    'Neo Discovery 1st Edition',
    'Neo Revelation',
    'Neo Revelation 1st Edition',
    'Neo Destiny',
    'Neo Destiny 1st Edition',
  ],
  'e-Card (2002-2003)': [
    'Expedition',
    'Aquapolis',
    'Skyridge',
  ],
  'EX 시리즈 (2003-2007)': [
    'EX Ruby & Sapphire',
    'EX Sandstorm',
    'EX Dragon',
    'EX Team Magma vs Team Aqua',
    'EX Hidden Legends',
    'EX FireRed & LeafGreen',
    'EX Team Rocket Returns',
    'EX Deoxys',
    'EX Emerald',
    'EX Unseen Forces',
    'EX Delta Species',
    'EX Legend Maker',
    'EX Holon Phantoms',
    'EX Crystal Guardians',
    'EX Dragon Frontiers',
    'EX Power Keepers',
  ],
  'DP/HGSS (2007-2011)': [
    'Diamond & Pearl',
    'Mysterious Treasures',
    'Secret Wonders',
    'Great Encounters',
    'Majestic Dawn',
    'Legends Awakened',
    'Stormfront',
    'Platinum',
    'Rising Rivals',
    'Supreme Victors',
    'Arceus',
    'HeartGold & SoulSilver',
    'Unleashed',
    'Undaunted',
    'Triumphant',
    'Call of Legends',
  ],
  'BW/XY (2011-2016)': [
    'Black & White',
    'Emerging Powers',
    'Noble Victories',
    'Next Destinies',
    'Dark Explorers',
    'Dragons Exalted',
    'Boundaries Crossed',
    'Plasma Storm',
    'Plasma Freeze',
    'Plasma Blast',
    'Legendary Treasures',
    'XY Base',
    'Flashfire',
    'Furious Fists',
    'Phantom Forces',
    'Primal Clash',
    'Roaring Skies',
    'Ancient Origins',
    'BREAKthrough',
    'BREAKpoint',
    'Fates Collide',
    'Steam Siege',
    'Evolutions',
  ],
  'SM/SWSH (2017-2022)': [
    'Sun & Moon Base',
    'Guardians Rising',
    'Burning Shadows',
    'Crimson Invasion',
    'Ultra Prism',
    'Forbidden Light',
    'Celestial Storm',
    'Lost Thunder',
    'Team Up',
    'Unbroken Bonds',
    'Unified Minds',
    'Hidden Fates',
    'Cosmic Eclipse',
    'Sword & Shield Base',
    'Rebel Clash',
    'Darkness Ablaze',
    'Vivid Voltage',
    'Shining Fates',
    'Battle Styles',
    'Chilling Reign',
    'Evolving Skies',
    'Fusion Strike',
    'Brilliant Stars',
    'Astral Radiance',
    'Lost Origin',
    'Silver Tempest',
  ],
  'SV 현행 (2023-)': [
    'Scarlet & Violet Base',
    'Paldea Evolved',
    'Obsidian Flames',
    'Paradox Rift',
    '151',
    'Paldean Fates',
    'Temporal Forces',
    'Twilight Masquerade',
    'Shrouded Fable',
    'Stellar Crown',
    'Surging Sparks',
    'Prismatic Evolutions',
  ],
  '일본판 특수': [
    'Trainer Magazine Promo',
    'CoroCoro Comic Promo',
    'Pokémon Web',
    'Tropical Mega Battle',
    'Air Mew',
    'No.1/2/3 Trainer Trophy',
    '20th Anniversary',
    '25th Anniversary',
  ],
  '프로모 / 한정': [
    'Black Star Promo',
    'POP Series Promo',
    'McDonald\'s Promo',
    'Celebrations',
    'Crown Zenith',
    'Generations',
    'Hidden Fates',
  ],
}

// flat 리스트 (검색/노출용)
export const ALL_SETS = Object.values(POKEMON_SETS).flat()

// ─── 발매 연도 옵션 ─────────────────────────────────────────
// 1996 (일본판 최초) → 현재 연도. 옵션은 내림차순 (최근 우선).
const CURRENT_YEAR = new Date().getFullYear()
export const RELEASE_YEARS = Array.from(
  { length: CURRENT_YEAR - 1996 + 1 },
  (_, i) => CURRENT_YEAR - i,
)

// ─── PSA / BGS / CGC 등급 점수 표 ───────────────────────────
// PSA: 1, 1.5, 2, 2.5, ..., 10
// BGS: 1, 1.5, ..., 10 (+ Black Label 10 / Pristine 10 등 별칭)
// CGC: 1, 1.5, ..., 10 + Perfect 10
export const GRADE_SCORES = ['10', '9.5', '9', '8.5', '8', '7.5', '7', '6.5', '6']

export const GRADE_RUBRIC = {
  '10': { label: 'GEM MINT', desc: '거의 완벽 — 4mm 이내 중앙, 모서리 흠 없음, 표면 무결' },
  '9.5': { label: 'MINT+', desc: 'BGS/CGC 전용. PSA에는 없는 중간 등급' },
  '9': { label: 'MINT', desc: '아주 미세한 결점만 허용 (육안 거의 안 보임)' },
  '8.5': { label: 'NM-MT+', desc: 'BGS/CGC 중간 등급' },
  '8': { label: 'NM-MT', desc: '약간의 흠 — 가벼운 모서리 마모, 미세 표면 흠' },
  '7.5': { label: 'NM+', desc: 'BGS/CGC 중간 등급' },
  '7': { label: 'NM (Near Mint)', desc: '눈에 띄는 흠 1-2개 — 모서리/표면 약한 마모' },
  '6.5': { label: 'EX-MT+', desc: 'BGS/CGC' },
  '6': { label: 'EX-MT', desc: '컬렉터블 하한선 — 가벼운 표면 마모 + 모서리 흠' },
}

// BGS 서브그레이드 — 카드 4면 평가 (1-10 각각)
export const BGS_SUBGRADE_FIELDS = [
  { key: 'centering', label: '중앙 (Centering)', desc: '인쇄가 카드 중앙에 얼마나 정확히 자리잡았는지' },
  { key: 'corners',   label: '모서리 (Corners)',  desc: '4모서리의 마모/구부러짐 정도' },
  { key: 'edges',     label: '가장자리 (Edges)',  desc: '4변의 흰화/스크래치' },
  { key: 'surface',   label: '표면 (Surface)',    desc: '인쇄면의 스크래치/지문/얼룩' },
]
